import { describe, it, expect, beforeAll, afterAll } from 'bun:test';
import { existsSync, statSync } from 'fs';
import puppeteer from 'puppeteer';

// Import the function to test
import { convertHtmlToPdf } from '../../src/utils/pdf';
import { setupTestEnvironment, getTestFilePath } from '../test-utils';

// Increase test timeout since browser operations can take a while
const TEST_TIMEOUT = 30000;

describe('PDF Integration Tests', () => {
  beforeAll(async () => {
    await setupTestEnvironment();
    
    // Ensure Puppeteer can find the browser
    process.env.PUPPETEER_EXECUTABLE_PATH = require('puppeteer').executablePath();
  }, TEST_TIMEOUT);

  afterAll(async () => {
    // Close any remaining browser instances
    const browser = await puppeteer.connect({
      browserWSEndpoint: process.env.BROWSER_WS_ENDPOINT,
    }).catch(() => null);
    
    if (browser) {
      await browser.close();
    }
    
    // Uncomment to clean up after tests
    // await cleanupTestEnvironment();
  });

  it('should convert HTML to PDF', async () => {
    const testHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <title>Test PDF</title>
        </head>
        <body>
          <h1>Test PDF Generation</h1>
          <p>This is a test PDF generated by the integration test.</p>
        </body>
      </html>
    `;

    const outputPath = getTestFilePath('test-output.pdf');
    
    try {
      await convertHtmlToPdf(testHtml, outputPath);
      
      // Verify the PDF was created
      expect(existsSync(outputPath)).toBe(true);
      
      // Get file size using Node.js fs.statSync
      const stats = statSync(outputPath);
      expect(stats.size).toBeGreaterThan(1024);
    } catch (error) {
      console.error('Error during PDF generation:', error);
      throw error;
    }
  });
});
